import Head from "next/head";
import React, { useState } from "react";
import styles from "../styles/Home.module.css";
import Header from "../comps/Header";

export default function Home() {
  const [fetchedData, setFetchedData] = useState({});

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <h1>Hello there.</h1>
    </div>
  );
}
